### ISSUE TITLE
海外用户；切换网络时如果万一重连失败后无法再次重连的BUG（内详）

### ISSUE THREAD

**Issue by mgttt** [netease-kit/NIM_iOS_UIKit#150]
### 问题描述与现象

海外用户，在切换网络时（电信流量转WIFI或WIFI转WIFI时，真机和模拟器都有一定机会测试出），如果万一自动重连失败后，就无法再次自动或手动重连，只有把app关掉重开才没事。

#### 是否重现

如上问题所述。

#### 其它备注

初步查LOG可以基本确定是 切换网络时某些特别时机时，原通信通道的加密证书失效，但SDK未能识别并自动重连正确节点，此时网络连接的 NSUrlConnection和NSUrlSession类中的 TLS缓存失败而没有释放

### 建议解决方案

修改SDK，增加两点逻辑
1，网络变化时自行判断 网络恢复 且 .isLogined=NO时，判断这种情况时应该释放缓存等再重试
2，允许调用者进行手动解构（并释放所有的 网络连接），这一点也是针对不要乱用 单例，因为单例会导致呼叫者无法实现多开（多用户同时登陆）这个需求。

### PS

虽然不知道为什么 NIMSDK要闭源，不过如果你们把它开源的话，我有能力把它给FIX掉。

**Comment by xiangwangfeng** [comment]
有没有相应的 log 和问题发生的时间点可以提供我们分析一下。
NIMSDK 底层连接并不使用 http(s) 相关服务，使用的是 TCP 连接。
